name: CI
on:
  push:
    branches:
      - "main"

concurrency:  ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    if: 
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache:  "pnpm"

      - run: pnpm install --frozen-lockfile
      - name: Create Release Pull Request or Publish
        id: changesets
        uses: changesets/action@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          publish:  pnpm run build
        env:
          GITHUB_TOKEN: ${{ github.token }}
          
      - name: Publish to npm
        run: |
          npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
          pnpm run build
          npm publish --ignore-scripts --access public
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}